/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_krakenapps_winapi_MemoryStatus */

#ifndef _Included_org_krakenapps_winapi_MemoryStatus
#define _Included_org_krakenapps_winapi_MemoryStatus
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_krakenapps_winapi_MemoryStatus
 * Method:    getMemoryStatus
 * Signature: (Lorg/krakenapps/winapi/MemoryStatus;)V
 */
JNIEXPORT void JNICALL Java_org_krakenapps_winapi_MemoryStatus_getMemoryStatus
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
