// **********************************************************************
//
// Copyright (c) 2003-2010 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************

// Ice version 3.4.1

package IceBox;

// <auto-generated>
//
// Generated from file `IceBox.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>


public interface _ServiceObserverDel extends Ice._ObjectDel
{
    void servicesStarted(String[] services, java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;

    void servicesStopped(String[] services, java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;
}
