// **********************************************************************
//
// Copyright (c) 2003-2010 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************

// Ice version 3.4.1

package Ice;

// <auto-generated>
//
// Generated from file `Locator.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>


public final class _LocatorDelD extends Ice._ObjectDelD implements _LocatorDel
{
    public Ice.ObjectPrx
    findAdapterById(final String id, java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper,
               AdapterNotFoundException
    {
        throw new Ice.CollocationOptimizationException();
    }

    public Ice.ObjectPrx
    findObjectById(final Identity id, java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper,
               ObjectNotFoundException
    {
        throw new Ice.CollocationOptimizationException();
    }

    public LocatorRegistryPrx
    getRegistry(java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper
    {
        final Ice.Current __current = new Ice.Current();
        __initCurrent(__current, "getRegistry", Ice.OperationMode.Nonmutating, __ctx);
        final LocatorRegistryPrxHolder __result = new LocatorRegistryPrxHolder();
        IceInternal.Direct __direct = null;
        try
        {
            __direct = new IceInternal.Direct(__current)
            {
                public Ice.DispatchStatus run(Ice.Object __obj)
                {
                    Locator __servant = null;
                    try
                    {
                        __servant = (Locator)__obj;
                    }
                    catch(ClassCastException __ex)
                    {
                        throw new Ice.OperationNotExistException(__current.id, __current.facet, __current.operation);
                    }
                    __result.value = __servant.getRegistry(__current);
                    return Ice.DispatchStatus.DispatchOK;
                }
            };
            try
            {
                Ice.DispatchStatus __status = __direct.servant().__collocDispatch(__direct);
                if(__status == Ice.DispatchStatus.DispatchUserException)
                {
                    __direct.throwUserException();
                }
                assert __status == Ice.DispatchStatus.DispatchOK;
                return __result.value;
            }
            finally
            {
                __direct.destroy();
            }
        }
        catch(Ice.SystemException __ex)
        {
            throw __ex;
        }
        catch(java.lang.Throwable __ex)
        {
            IceInternal.LocalExceptionWrapper.throwWrapper(__ex);
        }
        return __result.value;
    }
}
