// **********************************************************************
//
// Copyright (c) 2003-2010 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************

// Ice version 3.4.1

package Ice;

// <auto-generated>
//
// Generated from file `LocalException.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>


/**
 * This exception indicates that a message did not start with the expected
 * magic number ('I', 'c', 'e', 'P').
 * 
 **/
public class BadMagicException extends ProtocolException
{
    public BadMagicException()
    {
        super();
    }

    public BadMagicException(String reason, byte[] badMagic)
    {
        super(reason);
        this.badMagic = badMagic;
    }

    public String
    ice_name()
    {
        return "Ice::BadMagicException";
    }

    /**
     * A sequence containing the first four bytes of the incorrect message.
     * 
     **/
    public byte[] badMagic;
}
