// **********************************************************************
//
// Copyright (c) 2003-2010 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************

// Ice version 3.4.1

package Ice;

// <auto-generated>
//
// Generated from file `Router.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>


/**
 * Add new proxy information to the router's routing table.
 * 
 * <p class="Deprecated">This operation is deprecated, and only used for old
 * Ice clients (older than version 3.1).
 * 
 * @deprecated addProxy() is deprecated, use addProxies() instead.
 **/

public abstract class Callback_Router_addProxy extends Ice.OnewayCallback
{
}
