// **********************************************************************
//
// Copyright (c) 2003-2010 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************

// Ice version 3.4.1

package Ice;

// <auto-generated>
//
// Generated from file `Connection.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>


/**
 * Base class providing access to the connection details.
 * 
 **/
public class ConnectionInfo
{
    public ConnectionInfo()
    {
    }

    public ConnectionInfo(boolean incoming, String adapterName)
    {
        this.incoming = incoming;
        this.adapterName = adapterName;
    }

    /**
     * Whether or not the connection is an incoming or outgoing
     * connection.
     * 
     **/
    public boolean incoming;

    /**
     * The name of the adapter associated with the connection.
     * 
     **/
    public String adapterName;
}
