// **********************************************************************
//
// Copyright (c) 2003-2010 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************

// Ice version 3.4.1

package Ice;

// <auto-generated>
//
// Generated from file `LocalException.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>


/**
 * This exception is raised if no facet with the given name exists,
 * but at least one facet with the given identity exists.
 * 
 **/
public class FacetNotExistException extends RequestFailedException
{
    public FacetNotExistException()
    {
        super();
    }

    public FacetNotExistException(Identity id, String facet, String operation)
    {
        super(id, facet, operation);
    }

    public String
    ice_name()
    {
        return "Ice::FacetNotExistException";
    }
}
