// **********************************************************************
//
// Copyright (c) 2003-2010 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************

// Ice version 3.4.1

package Ice;

// <auto-generated>
//
// Generated from file `Endpoint.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>


/**
 * Provides access to the address details of a IP endpoint.
 * 
 * @see Endpoint
 * 
 **/
public abstract class IPEndpointInfo extends EndpointInfo
{
    public IPEndpointInfo()
    {
        super();
    }

    public IPEndpointInfo(int timeout, boolean compress, String host, int port)
    {
        super(timeout, compress);
        this.host = host;
        this.port = port;
    }

    /**
     * The host or address configured with the endpoint.
     * 
     **/
    public String host;

    /**
     * The port number.
     * 
     **/
    public int port;
}
