// **********************************************************************
//
// Copyright (c) 2003-2010 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************

// Ice version 3.4.1

package Ice;

// <auto-generated>
//
// Generated from file `LocalException.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>


/**
 * This exception indicates that a failure occurred while initializing
 * a plug-in.
 * 
 **/
public class PluginInitializationException extends Ice.LocalException
{
    public PluginInitializationException()
    {
    }

    public PluginInitializationException(String reason)
    {
        this.reason = reason;
    }

    public String
    ice_name()
    {
        return "Ice::PluginInitializationException";
    }

    /**
     * The reason for the failure.
     * 
     **/
    public String reason;
}
