// **********************************************************************
//
// Copyright (c) 2003-2010 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************

// Ice version 3.4.1

package Glacier2;

// <auto-generated>
//
// Generated from file `Session.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>


public interface _IdentitySetDel extends Ice._ObjectDel
{
    void add(Ice.Identity[] additions, java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;

    void remove(Ice.Identity[] deletions, java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;

    Ice.Identity[] get(java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;
}
