// **********************************************************************
//
// Copyright (c) 2003-2010 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************

// Ice version 3.4.1

package Glacier2;

// <auto-generated>
//
// Generated from file `Router.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>


public interface _RouterDel extends Ice._RouterDel
{
    String getCategoryForClient(java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;

    SessionPrx createSession(String userId, String password, java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper,
               CannotCreateSessionException,
               PermissionDeniedException;

    SessionPrx createSessionFromSecureConnection(java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper,
               CannotCreateSessionException,
               PermissionDeniedException;

    void refreshSession(java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper,
               SessionNotExistException;

    void destroySession(java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper,
               SessionNotExistException;

    long getSessionTimeout(java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;
}
