// **********************************************************************
//
// Copyright (c) 2003-2010 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************

// Ice version 3.4.1

package Glacier2;

// <auto-generated>
//
// Generated from file `Session.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>


public interface _SessionControlDel extends Ice._ObjectDel
{
    StringSetPrx categories(java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;

    StringSetPrx adapterIds(java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;

    IdentitySetPrx identities(java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;

    int getSessionTimeout(java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;

    void destroy(java.util.Map<String, String> __ctx)
        throws IceInternal.LocalExceptionWrapper;
}
