// **********************************************************************
//
// Copyright (c) 2003-2010 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************

// Ice version 3.4.1

package Glacier2;

// <auto-generated>
//
// Generated from file `PermissionsVerifier.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>


public final class PermissionsVerifierHolder extends Ice.ObjectHolderBase<PermissionsVerifier>
{
    public
    PermissionsVerifierHolder()
    {
    }

    public
    PermissionsVerifierHolder(PermissionsVerifier value)
    {
        this.value = value;
    }

    public void
    patch(Ice.Object v)
    {
        try
        {
            value = (PermissionsVerifier)v;
        }
        catch(ClassCastException ex)
        {
            IceInternal.Ex.throwUOE(type(), v.ice_id());
        }
    }

    public String
    type()
    {
        return _PermissionsVerifierDisp.ice_staticId();
    }
}
