// **********************************************************************
//
// Copyright (c) 2003-2010 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************

// Ice version 3.4.1

package Glacier2;

// <auto-generated>
//
// Generated from file `Session.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>


public final class StringSetPrxHolder
{
    public
    StringSetPrxHolder()
    {
    }

    public
    StringSetPrxHolder(StringSetPrx value)
    {
        this.value = value;
    }

    public StringSetPrx value;
}
