// **********************************************************************
//
// Copyright (c) 2003-2010 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************

// Ice version 3.4.1

package Ice;

// <auto-generated>
//
// Generated from file `Locator.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>


/**
 * Find an adapter by id and return its proxy (a dummy direct
 * proxy created by the adapter).
 * 
 **/

public abstract class Callback_Locator_findAdapterById extends Ice.TwowayCallback
{
    public abstract void response(Ice.ObjectPrx __ret);
    public abstract void exception(Ice.UserException __ex);

    public final void __completed(Ice.AsyncResult __result)
    {
        LocatorPrx __proxy = (LocatorPrx)__result.getProxy();
        Ice.ObjectPrx __ret = null;
        try
        {
            __ret = __proxy.end_findAdapterById(__result);
        }
        catch(Ice.UserException __ex)
        {
            exception(__ex);
            return;
        }
        catch(Ice.LocalException __ex)
        {
            exception(__ex);
            return;
        }
        response(__ret);
    }
}
