// **********************************************************************
//
// Copyright (c) 2003-2010 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************

// Ice version 3.4.1

package Ice;

// <auto-generated>
//
// Generated from file `Endpoint.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>


/**
 * Base class providing access to the endpoint details.
 * 
 **/
public abstract class EndpointInfo
{
    /**
     * Returns the type of the endpoint.
     * 
     **/
    public abstract short type();

    /**
     * Returns true if this endpoint is a datagram endpoint.
     * 
     **/
    public abstract boolean datagram();

    /**
     * Returns true if this endpoint is a secure endpoint.
     * 
     **/
    public abstract boolean secure();

    public EndpointInfo()
    {
    }

    public EndpointInfo(int timeout, boolean compress)
    {
        this.timeout = timeout;
        this.compress = compress;
    }

    /**
     * The timeout for the endpoint in milliseconds. 0 means
     * non-blocking, -1 means no timeout.
     * 
     **/
    public int timeout;

    /**
     * Specifies whether or not compression should be used if
     * available when using this endpoint.
     * 
     **/
    public boolean compress;
}
