// **********************************************************************
//
// Copyright (c) 2003-2010 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************

// Ice version 3.4.1

package Ice;

// <auto-generated>
//
// Generated from file `LocalException.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>


/**
 * This exception is raised if there was an error while parsing a
 * stringified identity.
 * 
 **/
public class IdentityParseException extends Ice.LocalException
{
    public IdentityParseException()
    {
    }

    public IdentityParseException(String str)
    {
        this.str = str;
    }

    public String
    ice_name()
    {
        return "Ice::IdentityParseException";
    }

    /**
     * The string that could not be parsed.
     * 
     **/
    public String str;
}
