// **********************************************************************
//
// Copyright (c) 2003-2010 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************

// Ice version 3.4.1

package Ice;

// <auto-generated>
//
// Generated from file `LocalException.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>


/**
 * Indicates that the response to a request has already been sent;
 * re-dispatching such a request is not possible.
 * 
 **/
public class ResponseSentException extends Ice.LocalException
{
    public String
    ice_name()
    {
        return "Ice::ResponseSentException";
    }
}
