package org.krakenapps.ber;

public enum UniversalTags {
	EndOfContent, BOOLEAN, INTEGER, BIT_STRING, OCTET_STRING, NULL, OID, OBJECT_DESCRIPTOR, EXTERNAL, REAL, ENUM, EMBEDDED_PDV, UTF8_STRING, RELATIVE_OID, SEQUENCE, SET, NUMERIC_STRING, PRINTABLE_STRING, T61_STRING, VIDEOTEX_STRING, IA5_STRING, UTC_TIME, GENERALIZED_TIME, GRAPHIC_STRING, VISIBLE_STRING, GENERAL_STRING, UNIVERSAL_STRING, CHARACTER_STRING, BMP_STRING
}