/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_krakenapps_winapi_AdapterInfo */

#ifndef _Included_org_krakenapps_winapi_AdapterInfo
#define _Included_org_krakenapps_winapi_AdapterInfo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_krakenapps_winapi_AdapterInfo
 * Method:    nativeGetAdapterInfos
 * Signature: ()Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_org_krakenapps_winapi_AdapterInfo_nativeGetAdapterInfos
  (JNIEnv *, jobject);

jobject getJavaObject(JNIEnv *, PIP_ADAPTER_INFO);

#ifdef __cplusplus
}
#endif
#endif
