/*
 * Copyright 2010 NCHOVY
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_krakenapps_winapi_RoutingTable */

#ifndef _Included_org_krakenapps_winapi_RoutingTable
#define _Included_org_krakenapps_winapi_RoutingTable
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     org_krakenapps_winapi_RoutingTable
 * Method:    getRoutingEntries
 * Signature: ()[Lorg/krakenapps/winapi/RoutingTable;
 */
JNIEXPORT jobjectArray JNICALL Java_org_krakenapps_winapi_RoutingTable_getRoutingEntries
  (JNIEnv *, jobject);

jobject getForwardRow(JNIEnv *, MIB_IPFORWARDROW);

#ifdef __cplusplus
}
#endif
#endif
