/*
 * Copyright 2010 NCHOVY
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_krakenapps_winapi_RegistryKey */

#ifndef _Included_org_krakenapps_winapi_RegistryKey
#define _Included_org_krakenapps_winapi_RegistryKey
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_krakenapps_winapi_RegistryKey
 * Method:    RegOpenKeyEx
 * Signature: (ILjava/lang/String;ILorg/krakenapps/winapi/impl/IntegerRef;)I
 */
JNIEXPORT jint JNICALL Java_org_krakenapps_winapi_RegistryKey_RegOpenKeyEx
  (JNIEnv *, jobject, jint, jstring, jint, jobject);

/*
 * Class:     org_krakenapps_winapi_RegistryKey
 * Method:    RegQueryValueEx
 * Signature: (ILjava/lang/String;Lorg/krakenapps/winapi/impl/IntegerRef;Lorg/krakenapps/winapi/impl/ByteArrayRef;)I
 */
JNIEXPORT jint JNICALL Java_org_krakenapps_winapi_RegistryKey_RegQueryValueEx
  (JNIEnv *, jobject, jint, jstring, jobject, jobject);

/*
 * Class:     org_krakenapps_winapi_RegistryKey
 * Method:    RegCloseKey
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_krakenapps_winapi_RegistryKey_RegCloseKey
  (JNIEnv *, jobject, jint);


JNIEXPORT jint JNICALL Java_org_krakenapps_winapi_RegistryKey_RegQueryInfoKey
  (JNIEnv *, jobject, jint, jobject, jobject, jobject, jobject, jobject, jobject, jobject, jobject);

JNIEXPORT jint JNICALL Java_org_krakenapps_winapi_RegistryKey_RegEnumKeyEx
  (JNIEnv *, jobject, jint, jint, jobject, jint, jobject);

JNIEXPORT jint JNICALL Java_org_krakenapps_winapi_RegistryKey_RegEnumValue
  (JNIEnv *, jobject, jint, jint, jobject, jint);


#ifdef __cplusplus
}
#endif
#endif
