/*
 * Copyright 2010 NCHOVY
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_krakenapps_winapi_IpGlobalProperties */

#ifndef _Included_org_krakenapps_winapi_IpGlobalProperties
#define _Included_org_krakenapps_winapi_IpGlobalProperties
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_krakenapps_winapi_IpGlobalProperties
 * Method:    getTcpConnections
 * Signature: (Z)[Lorg/krakenapps/winapi/TcpConnectionInformation;
 */
JNIEXPORT jobjectArray JNICALL Java_org_krakenapps_winapi_IpGlobalProperties_getTcpConnections
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     org_krakenapps_winapi_IpGlobalProperties
 * Method:    getUdpListeners
 * Signature: (Z)[Lorg/krakenapps/winapi/UdpListenerInformation;
 */
JNIEXPORT jobjectArray JNICALL Java_org_krakenapps_winapi_IpGlobalProperties_getUdpListeners
  (JNIEnv *, jobject, jboolean);

#define AF_INET6 23

#ifdef __cplusplus
}
#endif
#endif
