// **********************************************************************
//
// Copyright (c) 2003-2010 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************

// Ice version 3.4.1

package Glacier2;

// <auto-generated>
//
// Generated from file `Router.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>


/**
 * This category must be used in the identities of all of the client's
 * callback objects. This is necessary in order for the router to
 * forward callback requests to the intended client. If the Glacier2
 * server endpoints are not set, the returned category is an empty 
 * string.
 * 
 **/

public abstract class Callback_Router_getCategoryForClient extends Ice.TwowayCallback
{
    public abstract void response(String __ret);

    public final void __completed(Ice.AsyncResult __result)
    {
        RouterPrx __proxy = (RouterPrx)__result.getProxy();
        String __ret = null;
        try
        {
            __ret = __proxy.end_getCategoryForClient(__result);
        }
        catch(Ice.LocalException __ex)
        {
            exception(__ex);
            return;
        }
        response(__ret);
    }
}
