// **********************************************************************
//
// Copyright (c) 2003-2010 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************

// Ice version 3.4.1

package Glacier2;

// <auto-generated>
//
// Generated from file `Session.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>


/**
 * Access the object that manages the allowable object identities
 * for this session. 
 * 
 **/

public abstract class Callback_SessionControl_identities extends Ice.TwowayCallback
{
    public abstract void response(IdentitySetPrx __ret);

    public final void __completed(Ice.AsyncResult __result)
    {
        SessionControlPrx __proxy = (SessionControlPrx)__result.getProxy();
        IdentitySetPrx __ret = null;
        try
        {
            __ret = __proxy.end_identities(__result);
        }
        catch(Ice.LocalException __ex)
        {
            exception(__ex);
            return;
        }
        response(__ret);
    }
}
