// **********************************************************************
//
// Copyright (c) 2003-2010 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************

// Ice version 3.4.1

package Glacier2;

// <auto-generated>
//
// Generated from file `Router.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>


/**
 * This exception is raised if a client tries to destroy a session
 * with a router, but no session exists for the client.
 * 
 * @see Router#destroySession
 * 
 **/
public class SessionNotExistException extends Ice.UserException
{
    public String
    ice_name()
    {
        return "Glacier2::SessionNotExistException";
    }

    public void
    __write(IceInternal.BasicStream __os)
    {
        __os.writeString("::Glacier2::SessionNotExistException");
        __os.startWriteSlice();
        __os.endWriteSlice();
    }

    public void
    __read(IceInternal.BasicStream __is, boolean __rid)
    {
        if(__rid)
        {
            __is.readString();
        }
        __is.startReadSlice();
        __is.endReadSlice();
    }

    public void
    __write(Ice.OutputStream __outS)
    {
        Ice.MarshalException ex = new Ice.MarshalException();
        ex.reason = "exception Glacier2::SessionNotExistException was not generated with stream support";
        throw ex;
    }

    public void
    __read(Ice.InputStream __inS, boolean __rid)
    {
        Ice.MarshalException ex = new Ice.MarshalException();
        ex.reason = "exception Glacier2::SessionNotExistException was not generated with stream support";
        throw ex;
    }
}
