// **********************************************************************
//
// Copyright (c) 2003-2010 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************

// Ice version 3.4.1

package IceSSL;

// <auto-generated>
//
// Generated from file `ConnectionInfo.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>


/**
 * Provides access to the connection details of an SSL connection
 * 
 **/
public class ConnectionInfo extends Ice.IPConnectionInfo
{
    public ConnectionInfo()
    {
        super();
    }

    public ConnectionInfo(boolean incoming, String adapterName, String localAddress, int localPort, String remoteAddress, int remotePort, String cipher, String[] certs)
    {
        super(incoming, adapterName, localAddress, localPort, remoteAddress, remotePort);
        this.cipher = cipher;
        this.certs = certs;
    }

    /**
     * The negotiated cipher suite.
     **/
    public String cipher;

    /**
     * The certificate chain.
     **/
    public String[] certs;
}
